/*
 * Trigger Service Tests
 * Verifies trigger evaluation, runtime event dispatch, and failure isolation
 *
 * @author: WaterRun
 * @file: ClashSharp.Tests/Unit/Services/TriggerServiceTests.cs
 * @date: 2026-06-28
 */

using ClashSharp.Model;
using ClashSharp.Service;

namespace ClashSharp.Tests.Unit.Services;

/// <summary>Unit tests for trigger task evaluation and runtime event dispatch.</summary>
public sealed class TriggerServiceTests
{
    /// <summary>Verifies runtime events raised during an active evaluation are queued instead of dropped.</summary>
    [Fact]
    public async Task RuntimeEvents_WhenEvaluationIsActive_AreQueuedAndEvaluated()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new() { BlockFirstDispatch = true };
        FakeTriggerRuntimeEvents runtimeEvents = new();
        TriggerService service = CreateService(storagePath, actions, runtimeEvents);
        service.SaveTasks(
        [
            new TriggerTask(
                "queued",
                "Queued trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.AppEntered)],
                [new TriggerAction(TriggerActionKind.SendNotification, "queued")]),
        ]);

        runtimeEvents.Publish(new TriggerRuntimeEvent(TriggerEventKind.AppEntered));
        await actions.FirstDispatchStarted.Task.WaitAsync(TimeSpan.FromSeconds(2));

        runtimeEvents.Publish(new TriggerRuntimeEvent(TriggerEventKind.AppEntered));
        actions.ReleaseFirstDispatch.TrySetResult(null);

        await WaitUntilAsync(() => actions.DispatchValues.Count == 2);
        Assert.Equal(["queued", "queued"], actions.DispatchValues);
    }

    /// <summary>Verifies one failing trigger action is logged and does not prevent later matching triggers from running.</summary>
    [Fact]
    public async Task EvaluateAsync_WhenOneTriggerActionFails_ContinuesWithOtherTriggers()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new()
        {
            ThrowForValue = "fail",
        };
        FakeTriggerLog log = new();
        TriggerService service = CreateService(storagePath, actions, log: log);
        service.SaveTasks(
        [
            new TriggerTask(
                "failing",
                "Failing trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.AppEntered)],
                [new TriggerAction(TriggerActionKind.SendNotification, "fail")]),
            new TriggerTask(
                "passing",
                "Passing trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.AppEntered)],
                [new TriggerAction(TriggerActionKind.SendNotification, "pass")]),
        ]);

        IReadOnlyList<TriggerExecutionResult> results = await service.EvaluateAsync(
            new TriggerEvaluationContext(
                TriggerEventKind.AppEntered,
                0,
                0,
                TimeSpan.Zero,
                TimeOnly.MinValue,
                NotificationLevel.Default),
            CancellationToken.None);

        TriggerExecutionResult result = Assert.Single(results);
        Assert.Equal("passing", result.TaskId);
        Assert.Equal(["fail", "pass"], actions.DispatchValues);
        Assert.Contains(log.Entries, entry => entry.Level == "Warning" && entry.Category == "Trigger");
    }

    /// <summary>Verifies notification triggers do not re-enter from notifications generated by trigger actions.</summary>
    [Fact]
    public async Task RuntimeEvents_WhenNotificationTriggerSendsNotification_DoesNotReenterGeneratedNotification()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerRuntimeEvents runtimeEvents = new();
        int generatedNotificationEvents = 0;
        FakeTriggerActions actions = new()
        {
            AfterDispatch = kind =>
            {
                if (kind == ApplicationActionKind.SendNotification && generatedNotificationEvents < 2)
                {
                    generatedNotificationEvents++;
                    runtimeEvents.Publish(new TriggerRuntimeEvent(TriggerEventKind.NotificationRaised));
                }
            },
        };
        TriggerService service = CreateService(storagePath, actions, runtimeEvents);
        service.SaveTasks(
        [
            new TriggerTask(
                "notification-loop",
                "Notification loop",
                true,
                [new TriggerCondition(TriggerConditionKind.NotificationRaised)],
                [new TriggerAction(TriggerActionKind.SendNotification, "loop")]),
        ]);

        runtimeEvents.Publish(new TriggerRuntimeEvent(TriggerEventKind.NotificationRaised));

        await WaitUntilAsync(() => actions.DispatchValues.Count >= 1);
        await Task.Delay(100);
        Assert.Single(actions.DispatchValues);
    }

    /// <summary>Verifies starting the trigger service schedules periodic trigger evaluation.</summary>
    [Fact]
    public async Task Start_WhenPeriodicTriggerMatches_DispatchesPeriodicAction()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new();
        TriggerService service = CreateService(
            storagePath,
            actions,
            periodicInterval: TimeSpan.FromMilliseconds(20),
            createPeriodicContext: () => new TriggerEvaluationContext(
                TriggerEventKind.Periodic,
                0,
                0,
                TimeSpan.FromSeconds(5),
                TimeOnly.MinValue,
                NotificationLevel.Default));
        service.SaveTasks(
        [
            new TriggerTask(
                "periodic",
                "Periodic trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.Runtime, Threshold: 1)],
                [new TriggerAction(TriggerActionKind.SendNotification, "periodic")]),
        ]);

        try
        {
            service.Start();

            await WaitUntilAsync(() => actions.DispatchValues.Count >= 1);
            Assert.Contains("periodic", actions.DispatchValues);
        }
        finally
        {
            service.Stop();
        }
    }

    /// <summary>Verifies enabling triggers at runtime starts periodic evaluation after a disabled startup.</summary>
    [Fact]
    public async Task TriggersEnabled_WhenEnabledAfterDisabledStart_StartsPeriodicEvaluation()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new();
        bool triggersEnabled = false;
        TriggerService service = CreateService(
            storagePath,
            actions,
            periodicInterval: TimeSpan.FromMilliseconds(20),
            createPeriodicContext: () => new TriggerEvaluationContext(
                TriggerEventKind.Periodic,
                0,
                0,
                TimeSpan.FromSeconds(5),
                TimeOnly.MinValue,
                NotificationLevel.Default),
            getTriggersEnabled: () => triggersEnabled,
            setTriggersEnabled: value => triggersEnabled = value);
        service.SaveTasks(
        [
            new TriggerTask(
                "periodic-toggle",
                "Periodic toggle trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.Runtime, Threshold: 1)],
                [new TriggerAction(TriggerActionKind.SendNotification, "periodic-toggle")]),
        ]);

        try
        {
            service.Start();
            await Task.Delay(80);
            Assert.Empty(actions.DispatchValues);

            service.TriggersEnabled = true;

            await WaitUntilAsync(() => actions.DispatchValues.Count >= 1);
            Assert.Contains("periodic-toggle", actions.DispatchValues);
        }
        finally
        {
            service.Stop();
        }
    }

    /// <summary>Verifies disabling triggers at runtime stops periodic evaluation.</summary>
    [Fact]
    public async Task TriggersEnabled_WhenDisabledAfterStart_StopsPeriodicEvaluation()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new();
        bool triggersEnabled = true;
        TriggerService service = CreateService(
            storagePath,
            actions,
            periodicInterval: TimeSpan.FromMilliseconds(20),
            createPeriodicContext: () => new TriggerEvaluationContext(
                TriggerEventKind.Periodic,
                0,
                0,
                TimeSpan.FromSeconds(5),
                TimeOnly.MinValue,
                NotificationLevel.Default),
            getTriggersEnabled: () => triggersEnabled,
            setTriggersEnabled: value => triggersEnabled = value);
        service.SaveTasks(
        [
            new TriggerTask(
                "periodic-disable",
                "Periodic disable trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.Runtime, Threshold: 1)],
                [new TriggerAction(TriggerActionKind.SendNotification, "periodic-disable")]),
        ]);

        try
        {
            service.Start();
            await WaitUntilAsync(() => actions.DispatchValues.Count >= 1);

            service.TriggersEnabled = false;
            int dispatchCountAfterDisable = actions.DispatchValues.Count;
            await Task.Delay(120);

            Assert.False(triggersEnabled);
            Assert.Equal(dispatchCountAfterDisable, actions.DispatchValues.Count);
        }
        finally
        {
            service.Stop();
        }
    }

    /// <summary>Verifies the runtime trigger enablement switch immediately controls evaluation.</summary>
    [Fact]
    public async Task EvaluateAsync_WhenTriggersDisabledAtRuntime_DoesNotDispatchMatchingTask()
    {
        string storagePath = CreateTempStoragePath();
        FakeTriggerActions actions = new();
        bool triggersEnabled = true;
        TriggerService service = CreateService(
            storagePath,
            actions,
            getTriggersEnabled: () => triggersEnabled,
            setTriggersEnabled: value => triggersEnabled = value);
        service.SaveTasks(
        [
            new TriggerTask(
                "disabled",
                "Disabled trigger",
                true,
                [new TriggerCondition(TriggerConditionKind.AppEntered)],
                [new TriggerAction(TriggerActionKind.SendNotification, "disabled")]),
        ]);

        service.TriggersEnabled = false;
        IReadOnlyList<TriggerExecutionResult> results = await service.EvaluateAsync(
            new TriggerEvaluationContext(
                TriggerEventKind.AppEntered,
                0,
                0,
                TimeSpan.Zero,
                TimeOnly.MinValue,
                NotificationLevel.Default),
            CancellationToken.None);

        Assert.False(triggersEnabled);
        Assert.Empty(results);
        Assert.Empty(actions.DispatchValues);
    }

    private static TriggerService CreateService(
        string storagePath,
        FakeTriggerActions? actions = null,
        FakeTriggerRuntimeEvents? runtimeEvents = null,
        FakeTriggerLog? log = null,
        TimeSpan? periodicInterval = null,
        Func<TriggerEvaluationContext>? createPeriodicContext = null,
        Func<bool>? getTriggersEnabled = null,
        Action<bool>? setTriggersEnabled = null)
    {
        log ??= new FakeTriggerLog();
        return new TriggerService(
            storagePath,
            actions ?? new FakeTriggerActions(),
            new FakeTriggerNotifications(),
            runtimeEvents ?? new FakeTriggerRuntimeEvents(),
            log.Append,
            key => key switch
            {
                "Triggers.Log.Fired.Format" => "Trigger fired: {0}",
                "Triggers.Log.ActionFailed.Format" => "Trigger action failed: {0}",
                _ => key,
            },
            triggerEvent => new TriggerEvaluationContext(
                triggerEvent.EventKind,
                0,
                0,
                TimeSpan.Zero,
                TimeOnly.MinValue,
                triggerEvent.NotificationLevel),
            getTriggersEnabled,
            setTriggersEnabled,
            periodicInterval: periodicInterval,
            createPeriodicContext: createPeriodicContext);
    }

    private static string CreateTempStoragePath()
    {
        string directory = Path.Combine(Path.GetTempPath(), "ClashSharpTests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        return Path.Combine(directory, "Triggers.json");
    }

    private static async Task WaitUntilAsync(Func<bool> condition)
    {
        using CancellationTokenSource timeout = new(TimeSpan.FromSeconds(2));
        while (!condition())
        {
            await Task.Delay(20, timeout.Token);
        }
    }

    private sealed class FakeTriggerActions : IApplicationActionDispatcher
    {
        private int _dispatchCount;

        public List<string> DispatchValues { get; } = [];

        public bool BlockFirstDispatch { get; init; }

        public string? ThrowForValue { get; init; }

        public Action<ApplicationActionKind>? AfterDispatch { get; init; }

        public TaskCompletionSource<string> FirstDispatchStarted { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public TaskCompletionSource<object?> ReleaseFirstDispatch { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public async Task DispatchAsync(ApplicationActionKind kind, string value, CancellationToken cancellationToken)
        {
            DispatchValues.Add(value);
            int dispatchCount = Interlocked.Increment(ref _dispatchCount);
            if (dispatchCount == 1)
            {
                FirstDispatchStarted.TrySetResult(value);
                if (BlockFirstDispatch)
                {
                    await ReleaseFirstDispatch.Task.WaitAsync(cancellationToken);
                }
            }

            if (StringComparer.Ordinal.Equals(value, ThrowForValue))
            {
                throw new InvalidOperationException("action failed");
            }

            AfterDispatch?.Invoke(kind);
        }
    }

    private sealed class FakeTriggerNotifications : ITriggerNotificationSink
    {
        public void NotifyTriggerFired(string triggerName)
        {
        }
    }

    private sealed class FakeTriggerRuntimeEvents : ITriggerRuntimeEventSource
    {
        public event EventHandler<TriggerRuntimeEvent>? RuntimeEventRaised;

        public void Publish(TriggerRuntimeEvent triggerEvent)
        {
            RuntimeEventRaised?.Invoke(this, triggerEvent);
        }
    }

    private sealed class FakeTriggerLog
    {
        public List<LogEntry> Entries { get; } = [];

        public void Append(string level, string category, string message, string? detail)
        {
            Entries.Add(new LogEntry(level, category, message, detail));
        }
    }

    private sealed record LogEntry(string Level, string Category, string Message, string? Detail);
}
